--- #YAML:1.0
name:               Apache2-ApacheMobileFilter
version:            3.33
abstract:           ~
author:
    - Idel Fuschini (idel@idelfuschini.it)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Apache2::Connection:  0
    Apache2::Const:       0
    Apache2::Filter:      0
    Apache2::RequestRec:  0
    Apache2::RequestUtil:  0
    Apache2::SubRequest:  0
    APR::Table:           0
    Cache::FileBackend:   0
    Cache::Memcached:     1.27
    CGI::Cookie:          0
    File::Copy:           0
    Image::Resize:        0
    Image::Scale:         0
    Imager:               0
    IO::Uncompress::Unzip:  0
    LWP::Simple:          0
    POSIX:                0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
